# Lab C: Connection to the Backend & Advanced Functions

> **How long:** about 45 minutes  
> **Session shape:** the morning slot explains the route/data/UI changes; this notebook is the afternoon integration lab.

## 3.1 Define the Upgrade Before Editing

### Purpose

Keep the Day 2 upload -> chat loop working while adding three new behaviors:
1. answers come from retrieved chunks;
2. page numbers can open the PDF at that page;
3. a follow-up question can use earlier turns.

Target time: about 45 minutes.

### Before You Run

This notebook is the afternoon implementation lab. The morning lecture should already cover page mapping, multi-turn state, and how the new route flow differs from Day 2.

You should first finish Lab A and B. Keep using the same environment.

**Windows / cmd**

```bash
cd smartLearn-AI
.\.venv\Scripts\activate.bat
```

**macOS / Linux**

```bash
cd smartLearn-AI
source .venv/bin/activate
```

### Milestone for this lab

One uploaded PDF supports:
- RAG retrieval with numeric page citations;
- a PDF preview route;
- clickable page links in the frontend;
- one follow-up question in the same session.

> **How to use this notebook - Balanced Vibe Coding Mode**
>
> Stay disciplined about scope:
>
> - **Do directly:** reuse the Lab B document record, run one first-turn answer, append one follow-up turn, and read the stored history.
> - **Use Claude Code:** revise `smartlearn-backend/services/rag.py`, then wire `smartlearn-backend/main.py`, and only after that connect the frontend files.
>
> Assume Lab B already works: retrieval is page-aware, `answer_document(...)` already returns `answer + citations + sources`, and this notebook does not need to re-prove those pieces before route wiring starts.

## 3.2 Keep the Day 2 Contracts Stable

### Purpose

Use the Day 2 contracts as the starting point. Keep them recognizable so the frontend does not need a full rewrite.

```python
POST /upload?chat_id=day2-demo
response = {
    "status": "ok",
    "filename": "lesson.pdf",
    "pages": 12,
    "characters": 18432,
}

POST /chat
request = {
    "chat_id": "day2-demo",
    "message": "...",
}
response = {
    "answer": "...",
    "citations": [4, 8],
}
```

Day 3 may add one extra field such as `sources`, but the existing Day 2 request fields and visible meanings should stay the same.

In [4]:
import importlib
import sys
from pathlib import Path
from IPython.display import display

import pandas as pd

cwd = Path.cwd()
repo_name_candidates = ["smartLearn-AI"]
path_pairs = []
for repo_name in repo_name_candidates:
    path_pairs.extend([
        (cwd, cwd.parent / repo_name),
        (cwd / "Day3", cwd / repo_name),
        (cwd.parent / "Day3", cwd),
    ])

for day3_dir, repo_dir in path_pairs:
    backend_dir = repo_dir / "smartlearn-backend"
    if (
        (day3_dir / "pdf1.pdf").exists()
        and (backend_dir / "services" / "rag.py").exists()
    ):
        DAY3_DIR = day3_dir.resolve()
        REPO_DIR = repo_dir.resolve()
        BACKEND_DIR = backend_dir.resolve()
        break
else:
    raise FileNotFoundError(
        "Could not locate Day3/pdf1.pdf and smartLearn-AI/smartlearn-backend/services/rag.py from the current working directory."
    )

if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

from services import rag as rag_module

rag = importlib.reload(rag_module)
ARTIFACT_ROOT = DAY3_DIR / "artifacts"
ARTIFACT_ROOT.mkdir(parents=True, exist_ok=True)

ACTIVE_CHUNK_MODE = "character_overlap"
CHUNK_SIZE = 700
OVERLAP = 120
EMBED_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"
TOP_K = 3
CANDIDATE_POOL = 60
LAB_C_CHAT_ID = "day2-demo"
LAB_C_QUESTION_1 = "What is the name of the sparse retriever used in this paper?"
LAB_C_FOLLOWUP = "Give one more detail from that page."

print("Day3 folder:", DAY3_DIR)
print("Repository folder:", REPO_DIR)
print("Backend folder:", BACKEND_DIR)
print("Artifact root:", ARTIFACT_ROOT)

Day3 folder: C:\Users\nanfe\aiworkshop\Day3
Repository folder: C:\Users\nanfe\aiworkshop\smartLearn-AI
Backend folder: C:\Users\nanfe\aiworkshop\smartLearn-AI\smartlearn-backend
Artifact root: C:\Users\nanfe\aiworkshop\Day3\artifacts

> **Expected output:** the notebook prints the Day 3 folder, the artifact root, and the current embedding device.

## 3.3 Reuse the Lab B Record and Add History

### Purpose

This notebook continues from Lab B.
Assume `prepare_rag_document(...)`, `answer_document(...)`, page-aware retrieval hits, and the `answer + citations + sources` shape already work.

Now extend that working result into one Day 3 server-side record.
It is still an in-memory `documents[chat_id]` record, not database persistence.

```python
documents[chat_id] = {
    "filename": "lesson.pdf",
    "file_path": "smartlearn-backend/uploads/day2-demo.pdf",
    "pages": [...],
    "chunks": [...],
    "history": [
        {"question": "...", "answer": "...", "citations": [4]},
    ],
    "rag": {
        "document_id": "day2-demo",
        "index_path": "artifacts/indexes/lesson_character_overlap_all_MiniLM_L6_v2.faiss",
        "model_name": "sentence-transformers/all-MiniLM-L6-v2",
    },
}
```

Note: `history` is still temporary. A backend restart clears it.

### Vibe Coding walkthrough: inspect the Day 3 record shape

This step is the bridge from Lab B to Lab C. The retrieval pipeline already works; now the backend needs one document record that the app can keep in memory and reuse across later routes.

Read `rag.py` with one question in mind: what fields must be present so one uploaded PDF can support later upload, chat, citation, and history steps? Focus on the record shape and helper boundaries. If the file already does this, the correct result is no diff.

### Ask Claude Code

```text
Inspect smartlearn-backend/services/rag.py and do not edit yet.

Plan the smallest service-layer change so the app can do these three things cleanly:
- build one richer server-side record after upload, including the saved PDF path, page records, chunks, retrieval assets, and empty chat history;
- answer each new question from retrieved evidence, return page citations and short source previews, and keep the answer format stable for the frontend;
- remember earlier turns in memory so a follow-up question can use prior context while still retrieving fresh evidence again.

Keep these function names because later notebook checks will call them directly:
- `get_device() -> str`: input nothing; output `"cpu"` or `"cuda"` for setup checks.
- `extract_pages_for_rag(file_path: str | Path, page_limit: int | None = None) -> list[dict]`: input one local PDF path; output page records like `[{"page": 1, "text": "..."}]` for notebook tests.
- `relative_path_str(path: str | Path, base: str | Path) -> str`: input one artifact path and base folder; output a shorter display path.
- `extract_pages_from_bytes_for_rag(pdf_bytes: bytes) -> list[dict]`: input uploaded PDF bytes; output page records for the backend upload route.
- `prepare_rag_chat_record(chat_id: str, filename: str, pdf_bytes: bytes | None = None, pages: list[dict] | None = None, upload_root: str | Path | None = None, chunk_mode: str = "character_overlap", chunk_size: int = 700, overlap: int = 120, model_name: str = "sentence-transformers/all-MiniLM-L6-v2", batch_size: int = 32, artifact_root: str | Path | None = None) -> dict`: input one chat id, filename, and either uploaded bytes or page records; output an upload-time `documents[chat_id]` record with file path, pages, chunks, RAG metadata, and empty history.
- `build_upload_response(document: dict) -> dict`: input the richer server-side document record; output the visible upload success JSON for the frontend.
- `prepare_rag_document(document_id: str, filename: str, pages: list[dict], chunk_mode: str = "character_overlap", chunk_size: int = 700, overlap: int = 120, model_name: str = "sentence-transformers/all-MiniLM-L6-v2", batch_size: int = 32, artifact_root: str | Path | None = None) -> dict`: input page records and active settings; output a prepared document with chunks, embeddings, FAISS index metadata, and empty history.
- `search_document(question: str, document: dict, top_k: int = 3, candidate_pool: int = 60, history: list[dict] | None = None) -> list[dict]`: input one question and prepared document; output top-k retrieved chunks with page, chunk id, text, and score fields.
- `build_grounded_user_prompt(question: str, hits: list[dict], history: list[dict] | None = None) -> str`: input one question, retrieved hits, and recent history; output one grounded prompt string for answer generation.
- `answer_document(document: dict, question: str, top_k: int = 3, candidate_pool: int = 60, answer_model: str = "poolside/laguna-s-2.1:free") -> dict`: input one prepared document and question; output `answer`, `citations`, and `sources`.
- `answer_document_turn(document: dict, question: str, top_k: int = 3, candidate_pool: int = 60, answer_model: str = "poolside/laguna-s-2.1:free") -> dict`: input one prepared document and question; output the answer result plus the updated in-memory history.
- `append_history(document: dict, question: str, result: dict) -> list[dict]`: input the stored document, user question, and answer result; output the updated history list.
- `answer_chat_turn(document: dict, message: str, top_k: int = 3, candidate_pool: int = 60, answer_model: str = "poolside/laguna-s-2.1:free") -> dict`: input the stored route document and user message; output answer/citations/sources after fresh retrieval and in-memory history update.

For each function, preserve or add only the behavior needed for the three goals above.
Keep the chunk/page metadata reusable from notebook code.
Do not edit smartlearn-backend/main.py or any frontend file.
```

In [7]:
lab_c_pages = rag.extract_pages_for_rag(DAY3_DIR / "pdf1.pdf")

lab_c_document = rag.prepare_rag_document(
    document_id=LAB_C_CHAT_ID,
    filename="pdf1.pdf",
    pages=lab_c_pages,
    chunk_mode=ACTIVE_CHUNK_MODE,
    chunk_size=CHUNK_SIZE,
    overlap=OVERLAP,
    model_name=EMBED_MODEL_NAME,
    batch_size=32,
    artifact_root=ARTIFACT_ROOT,
)
lab_c_document["chat_id"] = LAB_C_CHAT_ID
lab_c_document["file_path"] = str(DAY3_DIR / "pdf1.pdf")

documents = {LAB_C_CHAT_ID: lab_c_document}

{
    "chat_id": LAB_C_CHAT_ID,
    "num_pages": len(lab_c_document["pages"]),
    "num_chunks": len(lab_c_document["chunks"]),
    "history_len": len(lab_c_document["history"]),
    "index_path": rag.relative_path_str(lab_c_document['artifacts']["index"], DAY3_DIR),
}

{'chat_id': 'day2-demo',
 'num_pages': 28,
 'num_chunks': 193,
 'history_len': 0,
 'index_path': 'artifacts\\day2-demo__index__character_overlap__s700__o120__sentence-transformers-all-MiniLM-L6-v2.faiss'}

> **Expected output:** one local document record exists in `documents[...]`, with an empty `history` list and a reusable FAISS index path for later route wiring.

## 3.4 Backend Routes: Store the Day 3 Record and Serve the Uploaded PDF

### Purpose

This merged lab covers two backend route changes: keep the visible Day 2 upload response unchanged while the server stores a richer RAG record, then expose that uploaded PDF through one stable backend URL.

### Route 1: Keep upload stable while changing what the server stores

This step updates only the backend upload route. Students should first locate the current Day 2 flow: validate PDF, read bytes, build the stored object, and return the success JSON.

The logic change is small: stop storing only a plain page list, and store one Day 3 RAG-ready record instead. The visible upload result should still look the same to the frontend.

### Ask Claude Code

```text
Inspect smartlearn-backend/main.py and smartlearn-backend/services/rag.py first. Do not edit yet.

Lab B already had a working upload route.
In this step, keep the same frontend-facing upload experience, but change the server-side storage so one upload creates a richer RAG-ready record.

Make the smallest possible diff in smartlearn-backend/main.py so POST /upload?chat_id=... does this:
- validate that the uploaded file is still a PDF
- read the uploaded bytes
- call the service-layer helper that prepares one Day 3 record for documents[chat_id]
- store that richer record under documents[chat_id]
- return the same visible Day 2 JSON shape for success
- fail cleanly without leaving a half-written record after an error

Keep the visible success shape as:
{"status": "ok", "filename": "...", "pages": 28, "characters": 18342}

Only edit smartlearn-backend/main.py.
Do not edit frontend files in this step.
```

### Later Backend Integration File

When you connect this notebook logic to the app, the route changes in this merged lab belong in:
- `smartLearn-AI/smartlearn-backend/main.py`

### Optional notebook smoke check

This cell only checks the upload-side storage shape inside Python.
The main proof for this merged lab should come from `uvicorn` `/docs` or a real browser page after both routes are in place.

### Optional notebook check: confirm the stored upload record

This check does two things together:
1. call `POST /upload?chat_id=...` through a local test client;
2. inspect `documents[chat_id]` in the same Python process.

If this step is correct, the visible response still looks like Day 2, but the stored backend record is already a Day 3 RAG record.

In [10]:
from services import rag as rag_module
rag = importlib.reload(rag_module)
from fastapi.testclient import TestClient
import importlib
import main as backend_main_module

backend_main = importlib.reload(backend_main_module)
client = TestClient(backend_main.app)

with (DAY3_DIR / "pdf1.pdf").open("rb") as f:
    upload_response = client.post(
        "/upload",
        params={"chat_id": LAB_C_CHAT_ID},
        files={"file": ("pdf1.pdf", f, "application/pdf")},
    )

upload_json = upload_response.json()
upload_record = backend_main.documents[LAB_C_CHAT_ID]

{
    "status_code": upload_response.status_code,
    "response": upload_json,
    "record_keys": sorted(upload_record.keys()),
    "history_len": len(upload_record["history"]),
    "page_count": len(upload_record["pages"]),
    "chunk_count": len(upload_record["chunks"]),
    "has_rag_meta": "rag" in upload_record,
    "saved_file_exists": Path(upload_record['saved_pdf_path']).exists(),
}

{'status_code': 200,
 'response': {'status': 'ok',
  'filename': 'pdf1.pdf',
  'pages': 28,
  'characters': 108878},
 'record_keys': ['artifacts',
  'batch_size',
  'chat_id',
  'chunk_mode',
  'chunk_size',
  'chunks',
  'embedding_dim',
  'filename',
  'history',
  'index',
  'manifest',
  'model_name',
  'num_chunks',
  'num_pages',
  'overlap',
  'pages',
  'paths',
  'saved_pdf_path'],
 'history_len': 0,
 'page_count': 28,
 'chunk_count': 193,
 'has_rag_meta': False,
 'saved_file_exists': True}

> **Expected output:** status code `200`; the JSON response still has `status`, `filename`, `pages`, and `characters`; the stored record now also contains `pages`, `chunks`, `history`, `rag`, and `file_path`.

### Route 2: Serve the Uploaded PDF by `chat_id`

Add one file-serving route so the browser can open the uploaded PDF by `chat_id`.

### Vibe Coding walkthrough: add one stable PDF URL for the current chat session

This step does not render the PDF yet. It only gives the frontend one backend URL that always points to the uploaded file for the current `chat_id`.

Find where the upload record already stores `file_path`, then add one small route that reads that path and returns the file safely. Keep missing-session behavior simple: invalid `chat_id` should still fail clearly.

### Ask Claude Code

```text
Inspect smartlearn-backend/main.py first. Do not edit yet.

The frontend needs one stable way to open the uploaded PDF for the current chat session.
Add the smallest possible route change so the browser can request one PDF by chat_id instead of guessing a filesystem path.

Make the smallest possible diff in smartlearn-backend/main.py so it adds:
@app.get("/documents/{chat_id}/file")

Requirements:
- look up the existing upload record from documents[chat_id]
- read the saved file path from that record
- return FileResponse(..., media_type="application/pdf")
- return 404 if chat_id is missing or if the saved file is missing
- keep unrelated routes untouched

Only edit smartlearn-backend/main.py.
Do not edit frontend files in this step.
```

### Verify in `/docs` or the browser

Launch backend

`uvicorn smartlearn-backend.main:app --reload`

Use `uvicorn` first because it proves both backend routes directly.

1. Open `http://127.0.0.1:8000/docs`.
2. Run `POST /upload` with one real `chat_id` such as `day3-demo` and upload `pdf1.pdf`.
3. Confirm status `200` and the same visible Day 2 response shape: `status`, `filename`, `pages`, `characters`.
4. In the same `/docs` page, or in a new browser tab, open `GET /documents/{chat_id}/file` with that same `chat_id`.
5. Confirm that the PDF itself opens in the browser.
6. Try one fake `chat_id` and confirm that the file route returns `404`.

If the frontend page is already running:
- upload should still succeed without changing the visible Day 2 upload behavior;
- if a PDF preview component has already been wired in later sections, that preview should open the same uploaded file;
- if the frontend does not render a PDF yet, that is expected at this checkpoint, so use `/docs` to verify the file route.

## 3.5 Backend Route: Multi-Turn Chat With Retrieve-Per-Turn

### Purpose

Keep the Day 2 request shape, but change the route internals so every turn retrieves evidence again and then appends history.

### Vibe Coding walkthrough: upgrade the chat route without changing the request shape

Students should first compare Day 2 and Day 3 chat behavior. Day 2 answered from one stored page list; Day 3 should answer from retrieval results and remember earlier turns in the same backend record.

The request body stays the same. The main change is inside the route: read the richer record, call the Day 3 helper, and keep history inside the same in-memory session.

### Ask Claude Code

```text
Inspect smartlearn-backend/main.py and smartlearn-backend/services/rag.py first. Do not edit yet.

Lab B already had a working POST /chat path.
In this step, keep the same frontend-facing request shape, but change the route internals so each new user turn runs the RAG search path and can also remember earlier turns.

Make the smallest possible diff in smartlearn-backend/main.py so POST /chat does this:
- keep the request shape {"chat_id": "...", "message": "..."}
- find the stored Day 3 record from documents[chat_id]
- call `rag.answer_chat_turn(document: dict, message: str, top_k: int = 3, candidate_pool: int = 60, answer_model: str = "poolside/laguna-s-2.1:free") -> dict`; input the stored Day 3 document record and user message, then return answer/citations/sources after fresh retrieval and history update
- return answer, citations, and sources from that result
- keep 404 for a missing chat_id record
- run retrieval again for every new question before answering
- append the completed turn into in-memory history after a successful answer

Only edit smartlearn-backend/main.py.
Do not edit frontend files in this step.
```

In a multi-turn route, the backend combines three things: the new question, the recent chat history, and the retrieved evidence. The goal is to keep context across turns without losing page-grounded support.

In [13]:
# Start this two-turn demo from a clean chat history.
lab_c_document["history"] = []

lab_c_turn1 = rag.answer_document_turn(
    lab_c_document,
    LAB_C_QUESTION_1,
    top_k=TOP_K,
    candidate_pool=CANDIDATE_POOL,
)

lab_c_followup_hits = rag.search_document(
    LAB_C_FOLLOWUP,
    lab_c_document,
    top_k=TOP_K,
    candidate_pool=CANDIDATE_POOL,
)

lab_c_followup_prompt = rag.build_grounded_user_prompt(
    LAB_C_FOLLOWUP,
    lab_c_followup_hits,
    history=lab_c_document["history"],
)

print("Stored history after turn 1:", len(lab_c_document["history"]))
print("-" * 60)
print(lab_c_followup_prompt[:1200])

Stored history after turn 1: 1
------------------------------------------------------------
Previous conversation:
Q: What is the name of the sparse retriever used in this paper?
A: Based on the provided context, the sparse retriever used in this paper is **BM25** [Page 6].

Context:
[Chunk from page 8]: MuSiQue MultiHop-RAG Ψ-RAG 74.85 76.94 47.83 55.18 w/o QR74.17(↓0.68)76.71(↓0.23)45.82(↓2.01)55.03(↓0.15) more effectively than the non-parametric RRF, but it does not provide a core performance contribution inΨ-RAG. (2)R&A agent is also beneficial for single-hop QA.For example, it brings a 1.89% F1 gain on NQ. This benefit stems from its query reorganization mechanism, which im- proves retrieval for queries with insufficient context. Query reorganization.Table 5 evaluates a counterpart of Ψ-RAG without query reorganization, that is, the R&A agent is no longer encouraged to reorganize and enrich their generated queries at each retrieval attempt. This leads to performance degradation across m

[Chunk from page 5]: . Three skewed datasets are generated from MultiHop-RAG (Tang & Yang, 2024): each combines the first 5 documents from one of three categories: “Business”, “Entertainment”, or “Technology”, with the first 50 documents from the semantically distant “Sports” class,

Without an API key, the local answer path still works but does not truly reason over history. The prompt preview above is the evidence that the grounded LLM path would receive earlier turns together with retrieved chunks.

In [14]:
# Keep this cell repeatable: rerunning it should replace turn 2, not append more turns.
lab_c_document["history"] = list(lab_c_turn1.get("history", [])[:1])

lab_c_turn2 = rag.answer_document_turn(
    lab_c_document,
    LAB_C_FOLLOWUP,
    top_k=TOP_K,
    candidate_pool=CANDIDATE_POOL,
)

history_df = pd.DataFrame(lab_c_document["history"])
print(lab_c_turn2["answer"])
print("Citations:", lab_c_turn2["citations"])

pd.set_option("display.max_colwidth", 200)
display(history_df)
display(pd.DataFrame(lab_c_turn2["sources"]))

I don't have access to the specific page content you're referring to, as the context provided doesn't include the page about Hotel Tallcorn or the other hotels mentioned in your previous conversation. The context chunks I have are from pages 5, 6, 8, and 22, but they don't contain information about hotels.

Could you please provide the specific page content or context chunk you'd like me to reference? Without knowing which page you're asking about, I cannot give you a detail from that page.
Citations: []

,question,answer,citations,sources,timestamp
0,What is the name of the sparse retriever used in this paper?,"Based on the provided context, the sparse retriever used in this paper is **BM25** [Page 6].",[6],"[{'page': 6, 'chunk_id': 50, 'score': 0.5374, 'preview': 'oˇcisk`y et al., 2018). We also use the first 100 documents from the LongBook subset in∞Bench (Zhang et al., 2024a), a narrative QA datase...",2026-08-03T08:59:18.348024+00:00
1,Give one more detail from that page.,"I don't have access to the specific page content you're referring to, as the context provided doesn't include the page about Hotel Tallcorn or the other hotels mentioned in your previous conversat...",[],"[{'page': 8, 'chunk_id': 65, 'score': 0.1658, 'preview': 'MuSiQue MultiHop-RAG Ψ-RAG 74.85 76.94 47.83 55.18 w/o QR74.17(↓0.68)76.71(↓0.23)45.82(↓2.01)55.03(↓0.15) more effectively than the non-pa...",2026-08-03T08:59:39.673441+00:00

,page,chunk_id,score,preview
0,8,65,0.1658,"MuSiQue MultiHop-RAG Ψ-RAG 74.85 76.94 47.83 55.18 w/o QR74.17(↓0.68)76.71(↓0.23)45.82(↓2.01)55.03(↓0.15) more effectively than the non-parametric RRF, but it does not provide a core performance c..."
1,5,44,0.1563,". Three skewed datasets are generated from MultiHop-RAG (Tang & Yang, 2024): each combines the first 5 documents from one of three categories: “Business”, “Entertainment”, or “Technology”, with th..."
2,22,146,0.1541,e NOT allowed. (3) Your summary should be NO MORE THAN {summary max length} WORDS. Keep in mind that a longer summary is not always better. An in-context example is provided below. ===============...

### Ask-Route Review Map

Check these points in the generated diff:
- the route reads `document["history"]`;
- the route appends both user and assistant turns after a successful answer;
- `citations` comes from the retrieved `sources`;
- a backend restart makes both the document record and the history disappear;
- the route still returns 404 for a fake `chat_id`.

> **Expected output:** one first-turn answer, one stored history row after turn 1, one follow-up prompt preview that includes history, and one second-turn answer with two rows in the local history table.

### Verify in `/docs` or the frontend page

Use `uvicorn` `/docs` first because it proves the backend route directly.

1. Open `http://127.0.0.1:8000/docs`.
2. Run `POST /upload` once with `chat_id=day3-demo` and upload `pdf1.pdf`.
3. Run `POST /chat` with a first question such as `What is the name of the sparse retriever used in this paper?`.
4. Confirm the response includes `answer`, numeric `citations`, and a `sources` list.
5. Run `POST /chat` again with the same `chat_id` and a follow-up such as `Give one more detail from that page.`.
6. Confirm the second response still returns citations and sources instead of behaving like a fresh empty session.
7. Restart the backend and confirm that the same `chat_id` now fails until you upload again.

Note: the Swagger `/docs` page only shows the latest `Response body`. The earlier answer is not kept on screen there, but the backend still keeps the same session history for that `chat_id`. Use the frontend page if you want to see the turns accumulate visually.

If the frontend page is already running:
- ask one question and confirm the answer appears;
- ask a follow-up in the same page and confirm it is appended as a new turn;
- if the backend was restarted, confirm the page shows the missing-session error until you upload again.

## 3.6 Frontend State Plan: Shared Upload Session and Active Page

### Purpose

Two pieces of state are now shared across components.

| State | Owner | Why |
| --- | --- | --- |
| `upload` | `App.jsx` | upload success already lives there and the preview can reuse the same session |
| `activePage` | `App.jsx` | chat changes it and preview reads it |

Keep `message`, `messages`, `loading`, and `error` inside `ChatPanel`.
Keep PDF rendering details inside `PdfPreview`.
When a new upload succeeds, reset `activePage` to `1` and reuse the existing `uploadKey` remount pattern so the old local message list disappears.

### Vibe Coding walkthrough: decide which state should be shared before editing components

Before touching the React files, decide what state really has to be shared across components. The upload/session result and the current page number should live high enough to be reused; message input and render details can stay local.

This planning step keeps the next edits small. The goal is not a new design. The goal is to connect the existing upload/chat page to one PDF preview and one page-jump flow.
After the main flow works, you can still make small spacing or panel-size adjustments if they help the page read more clearly.

### Ask Claude Code

```text
Inspect smartlearn-frontend/src/App.jsx, smartlearn-frontend/src/ChatPanel.jsx, smartlearn-frontend/src/api.js, and smartlearn-frontend/src/index.css first.
If PdfPreview.jsx does not exist, create only that one new file.

The frontend goal is to turn the existing Day 2 upload-and-chat page into one Day 3 page that can:
- keep the current upload session alive in shared state;
- preview the uploaded PDF;
- show a multi-turn message list;
- jump to a cited PDF page when the user clicks a page number.

Make the smallest possible diff so:
- App owns the shared upload state, the upload key, and the current page state
- PdfPreview can open the PDF route and jump with #page=...
- ChatPanel keeps a local multi-turn message list and can react to citation clicks
- the PDF preview stays on the left and the chat area stays on the right in one desktop workspace
- the chat area stays the same visual height as the PDF area and scrolls internally when the conversation grows
- extra messages must stay inside the right chat panel with its own scrollbar, instead of making the whole page or the PDF panel grow taller
- the existing upload and chat helpers remain usable

Do not edit backend files in this step.
Do not rewrite unrelated styling or component structure.
```

### Later Frontend Integration Files

When you connect Sections 3.6 to 3.9 to the app, the files to change are:
- `smartLearn-AI/smartlearn-frontend/src/App.jsx`
- `smartLearn-AI/smartlearn-frontend/src/ChatPanel.jsx`
- `smartLearn-AI/smartlearn-frontend/src/PdfPreview.jsx` (new)

### Verify in the frontend page

This section is about state placement, so the proof is visible only after Sections 3.7 to 3.9 are wired.

Use the running frontend page and check:
1. upload one PDF and confirm a preview area appears;
2. ask one question and click one citation so the preview moves away from page 1;
3. upload the PDF again or upload a second PDF;
4. confirm the preview resets back to page 1;
5. confirm the old chat list disappears after the new upload instead of staying on screen.

If either the preview stays on the old page or the old chat turns remain visible after a new upload, the shared-state wiring is still wrong.

## 3.7 Frontend Component: `PdfPreview` for File Loading and Page Jumps

### Purpose

Create one small preview component that can open the current PDF session and jump to a cited page.

### Vibe Coding walkthrough: build the smallest preview component that can follow page jumps

This component can stay simple. An iframe is enough for this workshop as long as it opens the current session file and updates the page number when the user clicks a citation.

Keep the change narrow: one preview component, one route-based URL, and one clear placeholder when no file is loaded.

### Ask Claude Code

```text
Inspect smartlearn-frontend/src/App.jsx and any existing preview-related code first. Do not edit yet.
If PdfPreview.jsx does not exist, create only that one new file.

Add the smallest possible preview component so the frontend can show the uploaded PDF for the current chat session and jump to a cited page.

Use this component contract:
- `PdfPreview({ upload, activePage, previewKey }) -> JSX.Element`: input the current upload response object or `null`, the active page number, and a refresh key; output either an empty placeholder or an iframe preview for the current PDF page.
- `getDocumentFileURL(page: number = 1) -> string`: input one page number; output the backend PDF file URL with `#page=${page}`.

Required behavior:
- accept the current upload/session and active page as props
- build the PDF URL from the same chat_id session used by the backend route, for example /documents/${CHAT_ID}/file
- append #page=${activePage} to the URL
- refresh the preview when activePage changes
- show a simple placeholder when no upload/session is loaded

A minimal iframe-based preview is enough.
Do not redesign unrelated UI.
Do not edit backend files.
```

A page citation becomes much more useful when the reader can jump to it directly. This preview component keeps the visible PDF page aligned with the page number returned by the chat answer.

### Preview-Component Review Map

Check the generated component for:
- the shared `chat_id`, not the original filename, in the route path;
- `#page=` in the final URL;
- one visible current-page label;
- no secrets or backend-only variables in the frontend.

### Verify in the frontend page

1. Open the frontend page and upload `pdf1.pdf`.
2. Confirm a PDF preview area appears instead of an empty placeholder.
3. Ask one question that returns a page citation.
4. Click that page citation.
5. Confirm the preview moves to the cited page and the preview label updates to the same page number.

If the preview stays blank, check the backend file route in `/docs` first. If the preview loads but never changes page, check whether the final preview URL includes `#page=`.

## 3.8 Frontend Component: `ChatPanel` for Multi-Turn Messages and Citation Clicks

### Purpose

Turn the old single-answer area into one multi-turn message list that can still call the existing chat helper.

Use a message shape like this:

```jsx
[
  { role: "user", content: "What is the main idea?" },
  {
    role: "assistant",
    content: "...",
    citations: [4, 8],
    sources: [
      { chunk_id: "chunk-0012", page: 4, preview: "..." },
    ],
  },
]
```

### Vibe Coding walkthrough: turn the answer area into a real multi-turn message list

The API helper can stay the same here. The main job is to stop thinking in terms of one answer box and start thinking in terms of a message list: user question, assistant answer, citations, and source previews for each turn.

Keep the UI logic local to `ChatPanel`. The parent only needs a callback for page jumps.

### Ask Claude Code

```text
Inspect smartlearn-frontend/src/ChatPanel.jsx and smartlearn-frontend/src/api.js first. Do not edit yet.

The goal is to keep the existing `askQuestion(message: string) -> Promise<{answer: string, citations: number[], sources: object[]}>` helper, but change the UI so one upload session can show several user/assistant turns instead of only one answer block.

Make the smallest possible diff so ChatPanel:
- keeps the component contract `ChatPanel({ enabled, onBusy, disabled, onJumpToPage }) -> JSX.Element`: input UI state flags and a page-jump callback; output the multi-turn chat panel
- keeps local message, messages, loading, and error state
- keeps using `askQuestion(message: string) -> Promise<{answer: string, citations: number[], sources: object[]}>` from src/api.js
- appends one user message and one assistant message per turn
- starts with an empty message list when a new upload remounts the panel
- stores returned citations and sources with each assistant message
- renders citation buttons from the citations list
- calls `onJumpToPage(page: number) -> void` when a citation button is clicked

Do not rewrite unrelated styling or backend code.
```

A multi-turn chat keeps earlier user and assistant messages so the next question has context. The frontend only needs a simple message list, but each assistant message should still carry its citation pages.

### Chat-Panel Review Map

After the diff is generated, check:
- where the new `messages` state is created;
- where old single-answer state is removed or replaced;
- where returned `citations` and `sources` are stored;
- where the click handler calls `onJumpToPage`;
- how the old message list is cleared when a new upload remounts the panel;
- what happens when the backend returns 404 after a restart.

### Verify in the frontend page

Launch frontend

`cd smartlearn-frontend`

`npm run dev`

1. Upload `pdf1.pdf`.
2. Ask one question and confirm the page shows one user turn and one assistant turn.
3. Ask a follow-up and confirm the page now shows four visible messages in order: user, assistant, user, assistant.
4. Confirm assistant turns show citation buttons instead of plain text-only output.
5. Click one citation button and confirm it can trigger a page jump.

If the second answer replaces the first one instead of being appended, the message-list state is still behaving like the old single-answer UI.

## 3.9 Frontend Component: `App.jsx` Coordinates Upload, Chat, and Preview

### Purpose

Let `App.jsx` coordinate the current upload session, the selected PDF page, and the remount key for a fresh chat list.

### Vibe Coding walkthrough: let `App.jsx` coordinate the shared session and current page

By this point, the child components already have clear roles. `App.jsx` only needs to hold the shared upload/session result, the current page number, and the remount key that clears old chat when a new file is uploaded.

The simplest logic is: upload succeeds -> reset page to 1 -> remount chat -> pass shared values down as props.

### Ask Claude Code

```text
Inspect smartlearn-frontend/src/App.jsx first. Do not edit yet.

The goal is to keep the existing Day 2 upload flow, but let App coordinate two new shared ideas:
- which upload/chat session is currently active
- which PDF page the preview should show after a citation click

Make the smallest possible diff so App:
- keeps the component role `App() -> JSX.Element`: input no props; output the full upload + preview + chat page
- uses a page-jump handler like `handleJumpToPage(page: number) -> void`: input one citation page number; update the shared active page state
- stores the current upload/session result in shared state
- stores the current active page in shared state
- resets the active page to 1 after a new upload succeeds
- bumps one remount key so the old local chat list disappears after a new upload
- passes the right props to ChatPanel and PdfPreview
- updates the active page when ChatPanel reports a citation click
- keeps the PDF preview on the left and the chat panel on the right, with the chat panel staying aligned in height and scrolling inside the panel
- keeps extra conversation turns inside the right chat panel with its own scrollbar, instead of stretching the whole page downward

Do not redesign unrelated layout or styling.
Do not edit backend files.
```

### Verify in the frontend page

This is the integration checkpoint for the whole frontend shell.

1. Upload `pdf1.pdf` and confirm the uploader, preview, and chat area all stay on one page.
2. Ask one question and click one citation.
3. Confirm the preview page changes while the existing chat turns remain visible.
4. Upload again and confirm both things happen together: the preview resets to page 1 and the old chat list is cleared.

If only one of those resets happens, `App.jsx` is not coordinating the shared state correctly.

## 3.10 End-to-End Test: Upload, Chat, Page Jump, and Follow-Up

### Purpose

Test one real flow from upload to follow-up question.

Use this order:
1. upload `pdf1.pdf` or another known PDF;
2. ask one question with a known answer page;
3. confirm the answer returns numeric citations;
4. click a cited page and verify the preview jumps;
5. ask a follow-up such as `Give one more detail from that page.`;
6. stop and restart the backend, then confirm you must upload again before `/chat` works.

> **Expected output:** One working cited answer, one working page jump, and one working follow-up turn.

## 3.11 Debug the Three Most Common Failures

| Symptom | First thing to check |
| --- | --- |
| answer text looks fine but the clicked page is wrong | was `citations` built from retrieved chunk pages or guessed from answer text? |
| clicking a page number does nothing | does the preview URL contain `#page=` and does `activePage` live in `App`? |
| the follow-up ignores earlier turns | is the route reading and updating `document["history"]` after each successful chat turn? |

## 3.12 Record Demo-Ready Evidence

Save three small pieces of evidence for Day 4:
- one screenshot of a cited answer;
- one screenshot or short clip of a page jump;
- one follow-up question that uses earlier context.

Write down:
- the PDF used;
- the question;
- the cited page numbers;
- whether the preview opened the expected page.

## 3.13 Commit the Cited Multi-Turn Milestone

### Purpose

This section connected backend citations, the PDF file route, page jumping, and follow-up chat into one flow. Save this working state after one full upload -> chat -> click -> follow-up test passes.

### Step 1: Confirm the section evidence

Before Git commands, confirm:

- `/upload` still returns the Day 2 response shape;
- `GET /documents/{chat_id}/file` opens the uploaded PDF;
- `/chat` returns `answer`, `citations`, and `sources`;
- one citation click opens the expected page in the preview;
- one follow-up question reuses earlier turns in the same session.

If one item is missing, fix that first.

### Step 2: Inspect the working tree

From the `smartLearn-AI` repository root, run:

```bash
git status
```

These files should not be staged:

- uploaded PDFs and local screenshots or clips;
- `Day3/artifacts/` - local experiment outputs;
- `.env` - local secrets;
- `.venv/`, `__pycache__/`, and `*.pyc` - local environment files;
- `node_modules/` and `dist/` - generated frontend files.

### Step 3: Review and stage only the route and UI files for this milestone

When your Day 3 frontend edits are all inside `smartlearn-frontend/src/`, you can review and stage that folder in one step.

Run:

```bash
git diff -- smartlearn-backend/services/rag.py smartlearn-backend/main.py smartlearn-frontend/src
git add smartlearn-backend/services/rag.py smartlearn-backend/main.py smartlearn-frontend/src
git status
git diff --staged
```

If you changed one extra helper file intentionally, inspect it first and stage it only when you can explain why it belongs to this milestone.

### Step 4: Create and verify the commit

Run:

```bash
git commit -m "feat: add cited multi-turn RAG flow"
git log -1 --oneline
git status
```

> **Expected output:** One commit records the cited multi-turn flow, and a fresh local upload-and-chat test still works after the commit.

In [ ]:
git status
git diff -- smartlearn-backend/services/rag.py smartlearn-backend/main.py smartlearn-frontend/src
git add smartlearn-backend/services/rag.py smartlearn-backend/main.py smartlearn-frontend/src
git status
git diff --staged
git commit -m "feat: add cited multi-turn RAG flow"
git log -1 --oneline
git status

> ✅ **Checkpoint 17 — The cited multi-turn milestone is committed:** The repo records the backend route updates and the preview/chat UI changes, and one full cited conversation still works after the commit.
>
> **If it does not match:** Unstage unrelated files, rerun one upload-and-ask flow, and commit only after you can explain every staged backend and frontend change.

## 3.14 Lab C Checkpoint

- [ ] `/upload` still returns the Day 2 response shape.
- [ ] The backend record stores `pages`, `chunks`, retrieval assets, and `history`.
- [ ] `GET /documents/{chat_id}/file` serves the uploaded PDF.
- [ ] `/chat` returns `answer`, `citations`, and `sources`.
- [ ] The frontend renders a multi-turn message list.
- [ ] Clicking a citation opens the expected page in the preview.
- [ ] A follow-up question uses earlier turns in the same session.

**Expected output**
- `smartlearn-backend/services/rag.py`
- one updated `smartlearn-backend/main.py`
- one new `smartlearn-frontend/src/PdfPreview.jsx`
- one updated `smartlearn-frontend/src/ChatPanel.jsx`
- one updated `smartlearn-frontend/src/App.jsx`

**Homework for Day 4**
1. Add one follow-up question that depends on the previous answer.
2. Add one test case where the answer should be `not found`.
3. Write one sentence about why a backend restart resets both the uploaded record and the chat history.

## Appendix A: Store Conversation History with PostgreSQL + SQLAlchemy

This appendix is an optional upgrade. Do it only after the main Lab C path works.

### Goal

Keep chat history in a real database so it survives backend restarts and can later be shared across multiple backend workers.

### What Is PostgreSQL?

<img src="https://media.licdn.com/dms/image/v2/D5612AQH45DKHSo-xWQ/article-cover_image-shrink_720_1280/B56ZlnRRr7H8AI-/0/1758374207017?e=2147483647&v=beta&t=YkmmB-0iWsTD-X7vRpIjWG6GUGxtWwszVT5rqhqUXqI" alt="img" style="zoom:40%;" />

PostgreSQL is a relational database. You store data in tables with rows and columns, connect those tables with ids, and query the saved data later.

For this workshop, one practical use is:
- one `conversations` table stores one row per `chat_id`;
- one `messages` table stores every user / assistant turn for that conversation;
- each message row keeps one role-specific message; assistant rows can also keep `citations_json` and created time.

Why this fits Day 3:
- message history no longer lives only in one Python dict;
- one backend restart no longer deletes the saved turns;
- later the same history can be read by more than one app worker.

### What Is SQLAlchemy?

SQLAlchemy is the Python layer that helps your app talk to PostgreSQL.

In this appendix, it does three jobs:
- define Python classes that map to database tables;
- open one engine and session factory from the DB URL;
- read and write conversation rows without hand-writing every SQL query.

### One Simple Table Shape

```python
Conversation(
    id,
    chat_id,
    filename,
    created_at,
)

Message(
    id,
    conversation_id,
    role,
    content,
    citations_json,
    created_at,
)
```

One question-answer turn usually becomes two message rows here: one `user` row and one `assistant` row. When the app reads history back, it can rebuild those rows into the same turn-style history list used in Lab C.

### Setup Before Coding

First install the Python packages inside the project environment:

```cmd
pip install sqlalchemy "psycopg[binary]"
```

Don't forget to add them to `smartLearn-AI/smartlearn-backend/requirements.txt`.

Then install and start PostgreSQL. We will use the same beginner-friendly local database URL on all systems:

```text
postgresql+psycopg://postgres:postgres@127.0.0.1:5432/smartlearn_day3
```

#### Windows

1. Download the Windows installer from the [PostgreSQL Windows download page](https://www.postgresql.org/download/windows/). Choose the [EDB installer](https://www.enterprisedb.com/downloads/postgres-postgresql-downloads).
2. During installation, keep port `5432`, set the `postgres` user password to `postgres`, and install the command-line tools.

If Chocolatey is already installed, you can also use an Administrator `cmd` window:

```cmd
choco install postgresql18 --params "/Password:postgres /Port:5432" -y
```

Chocolatey downloads and runs the PostgreSQL installer for you. The direct installer path is easier to follow; the Chocolatey path is faster when the package manager is already set up.

3. Open a new `cmd` window and check that `psql` works:

```cmd
psql -h 127.0.0.1 -p 5432 -U postgres -d postgres
```

4. In `psql`, create the workshop database:

```sql
CREATE DATABASE smartlearn_day3;
\q
```

If `psql` is not recognized, add PostgreSQL's `bin` folder to PATH. It is usually similar to `C:\Program Files\PostgreSQL\16\bin`.

If your notebook kernel runs in Windows, use the Windows installer path above. A PostgreSQL installed inside WSL may need extra Windows-to-WSL port forwarding before a Windows notebook can connect to it.

#### macOS

Use [Homebrew](https://brew.sh/) with the [PostgreSQL macOS download guide](https://www.postgresql.org/download/macosx/):

```bash
brew install postgresql
brew services start postgresql
createuser -s postgres
psql -d postgres -c "ALTER USER postgres WITH PASSWORD 'postgres';"
createdb -O postgres smartlearn_day3
psql -h 127.0.0.1 -p 5432 -U postgres -d smartlearn_day3
```

If `createuser` or `createdb` says the role or database already exists, continue to the final `psql` connection check.

#### Linux: Ubuntu / Debian

Use `apt` with the [PostgreSQL Ubuntu download guide](https://www.postgresql.org/download/linux/ubuntu/):

```bash
sudo apt update
sudo apt install postgresql postgresql-contrib
sudo systemctl start postgresql
sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'postgres';"
sudo -u postgres createdb smartlearn_day3
psql -h 127.0.0.1 -p 5432 -U postgres -d smartlearn_day3
```

If `createdb` says the database already exists, continue to the final `psql` connection check.

#### Set the DB URL for the Notebook

If you start Jupyter from `cmd`, set the variable before launching Jupyter from the same window:

```cmd
set DAY3_DB_URL=postgresql+psycopg://postgres:postgres@127.0.0.1:5432/smartlearn_day3
```

Inside a notebook, this one line is also enough before running the Appendix A cells:

```python
import os
os.environ["DAY3_DB_URL"] = "postgresql+psycopg://postgres:postgres@127.0.0.1:5432/smartlearn_day3"
```

When the final `psql` connection check works, the Appendix A database setup cell should be able to create the SQLAlchemy tables.

### Appendix Flow

1. Keep the current Day 3 PDF upload, chunking, retrieval, and answer path.
2. Use `chat_id` to find one conversation row in PostgreSQL.
3. Load older turns from the database before answering the new question.
4. Run retrieval again for the new question.
5. Save the new user message and assistant answer back into PostgreSQL, then rebuild turn-style history when reading it later.
6. Return the same `answer` / `citations` / `sources` shape to the frontend.

One important limit in the current project: the uploaded PDF record still lives in memory. If the backend restarts, the saved message history can stay in PostgreSQL, but the user still needs to upload the PDF again unless you later persist the document record too.

### Vibe Coding walkthrough: add an optional PostgreSQL history store without breaking the Day 3 main path

Use the current in-memory history path as the baseline. The appendix goal is not to replace it everywhere. The goal is to add one optional branch that keeps the same `/chat` response shape, but reads and writes history through PostgreSQL when a DB URL is configured.

### Ask Claude Code

```text
Inspect smartlearn-backend/services/rag.py, smartlearn-backend/main.py, and smartlearn-backend/requirements.txt first. Do not edit yet.

Appendix A goal:
keep the main Lab C path working, but add one optional PostgreSQL + SQLAlchemy path for conversation history.

Students should be able to:
- keep using the same upload route and the same chat request shape
- ask one question, ask a follow-up, and save both turns in PostgreSQL
- restart the backend, upload the PDF again, and still reuse the earlier saved history for the same chat_id

Use these helper entry names in smartlearn-backend/services/rag.py so the notebook can test them:
- `_require_sqlalchemy() -> dict[str, Any]`: input nothing; output the SQLAlchemy classes/functions used by this appendix or raise a clear ImportError.
- `build_history_engine(db_url: str) -> Engine`: input one `DAY3_DB_URL`; output a SQLAlchemy engine.
- `build_history_session_factory(engine) -> sessionmaker`: input one SQLAlchemy engine; output a factory that creates short database sessions.
- `ensure_history_tables(engine) -> None`: input one SQLAlchemy engine; create the conversation and message tables if they do not exist.
- `get_or_create_conversation(session, chat_id: str, filename: str | None = None) -> Conversation`: input one DB session, chat id, and optional filename; output the matching conversation row.
- `load_history_from_db(session, chat_id: str) -> list[dict]`: input one DB session and chat id; output previous turns in the same history-list shape used by the in-memory path.
- `store_history_turn(session, chat_id: str, question: str, result: dict, filename: str | None = None) -> list[dict]`: input one DB session, chat id, user question, and answer result; save user/assistant messages and output the updated history list.
- `answer_chat_turn_with_history_store(document: dict, chat_id: str, message: str, session_factory, top_k: int = 3, candidate_pool: int = 60, answer_model: str = "poolside/laguna-s-2.1:free") -> dict`: input a prepared document, chat id, user message, and DB session factory; output answer/citations/sources after loading old turns, retrieving fresh evidence, and saving the new turn.

Implementation requirements:
- add the required SQLAlchemy models for one conversation table and one message table
- keep answer_chat_turn as the default in-memory Lab C path
- treat PostgreSQL as an appendix-only optional branch
- keep POST /upload?chat_id=... unchanged
- keep GET /documents/{chat_id}/file unchanged
- keep POST /chat request unchanged: {"chat_id": "...", "message": "..."}
- keep the visible answer shape unchanged: {"answer": "...", "citations": [...], "sources": [...]}
- load older turns from PostgreSQL before answering the new message
- save the new turn to PostgreSQL after the answer is produced
- choose one simple switch such as the presence of DAY3_DB_URL to enable the appendix path
- add sqlalchemy and psycopg[binary] to smartLearn-AI/smartlearn-backend/requirements.txt

In smartlearn-backend/main.py:
- keep the current upload behavior
- keep the current non-database path working
- when DAY3_DB_URL is configured, route /chat to the new history-store helper instead of the pure in-memory helper
- do not require any frontend request-shape change

After editing, explain:
- where the DB URL is read
- which helper creates tables
- which helper loads old turns
- which helper writes one new turn
- why the frontend can keep the same ask/render contract
- what still does not survive restart in the current architecture
```

In [ ]:
import copy
import os
import time

os.environ["DAY3_DB_URL"] = "postgresql+psycopg://postgres:postgres@127.0.0.1:5432/smartlearn_day3"

rag = importlib.reload(rag_module)

APPENDIX_DB_URL = os.getenv("DAY3_DB_URL", "").strip()
APPENDIX_HELPERS = [
    "_require_sqlalchemy",
    "build_history_engine",
    "build_history_session_factory",
    "ensure_history_tables",
    "get_or_create_conversation",
    "load_history_from_db",
    "store_history_turn",
    "answer_chat_turn_with_history_store",
]
appendix_missing = [name for name in APPENDIX_HELPERS if not hasattr(rag, name)]
APPENDIX_READY = not appendix_missing and bool(APPENDIX_DB_URL)
APPENDIX_RUNTIME_READY = False
appendix_engine = None
appendix_session_factory = None

{
    "db_url_configured": bool(APPENDIX_DB_URL),
    "missing_helpers": appendix_missing,
    "next_step": (
        "Run the appendix prompt above, install sqlalchemy and psycopg[binary], and set DAY3_DB_URL in .env."
        if appendix_missing or not APPENDIX_DB_URL
        else "ready"
    ),
}

In [ ]:
if not APPENDIX_READY:
    print("Skip this cell until the helper functions exist and DAY3_DB_URL is configured.")
else:
    try:
        appendix_engine = rag.build_history_engine(APPENDIX_DB_URL)
        appendix_session_factory = rag.build_history_session_factory(appendix_engine)
        rag.ensure_history_tables(appendix_engine)
        APPENDIX_RUNTIME_READY = True

        appendix_engine_info = {
            "dialect": appendix_engine.url.get_backend_name(),
            "driver": appendix_engine.url.drivername,
            "host": appendix_engine.url.host,
            "database": appendix_engine.url.database,
            "tables_ready": True,
        }
        appendix_engine_info
    except ImportError as exc:
        print(exc)
    except Exception as exc:
        print(f"Database setup failed: {exc}")

In [ ]:
if not APPENDIX_RUNTIME_READY:
    print("Skip this cell until the database engine, session factory, and tables are ready.")
else:
    APPENDIX_DEMO_CHAT_ID = f"appendix-history-demo-{int(time.time())}"

    with appendix_session_factory() as session:
        rag.get_or_create_conversation(
            session,
            APPENDIX_DEMO_CHAT_ID,
            filename="pdf1.pdf",
        )
        rag.store_history_turn(
            session,
            APPENDIX_DEMO_CHAT_ID,
            question="What is the name of the sparse retriever used in this paper?",
            result={
                "answer": "The sparse retriever is BM25.",
                "citations": [4],
                "sources": [],
            },
            filename="pdf1.pdf",
        )
        rag.store_history_turn(
            session,
            APPENDIX_DEMO_CHAT_ID,
            question="Give one more detail from that page.",
            result={
                "answer": "It helps recover explicit facts that dense retrieval may miss.",
                "citations": [4],
                "sources": [],
            },
            filename="pdf1.pdf",
        )
        appendix_history = rag.load_history_from_db(session, APPENDIX_DEMO_CHAT_ID)

    appendix_history_df = pd.DataFrame(appendix_history)
    display(appendix_history_df)
    appendix_history_df

In [ ]:
if not APPENDIX_RUNTIME_READY:
    print("Skip this cell until the database engine, session factory, and tables are ready.")
else:
    APPENDIX_RAG_CHAT_ID = f"appendix-rag-demo-{int(time.time())}"
    appendix_document = copy.deepcopy(lab_c_document)
    appendix_document["history"] = []

    appendix_turn_1 = rag.answer_chat_turn_with_history_store(
        appendix_document,
        APPENDIX_RAG_CHAT_ID,
        LAB_C_QUESTION_1,
        session_factory=appendix_session_factory,
    )
    appendix_turn_2 = rag.answer_chat_turn_with_history_store(
        appendix_document,
        APPENDIX_RAG_CHAT_ID,
        LAB_C_FOLLOWUP,
        session_factory=appendix_session_factory,
    )

    with appendix_session_factory() as session:
        appendix_saved_history = rag.load_history_from_db(session, APPENDIX_RAG_CHAT_ID)

    appendix_turn_summary = pd.DataFrame([
        {
            "turn": 1,
            "citations": str(appendix_turn_1.get("citations", [])),
            "answer_preview": appendix_turn_1.get("answer", "")[:140],
            "history_len_after_turn": len(appendix_turn_1.get("history", [])),
        },
        {
            "turn": 2,
            "citations": str(appendix_turn_2.get("citations", [])),
            "answer_preview": appendix_turn_2.get("answer", "")[:140],
            "history_len_after_turn": len(appendix_turn_2.get("history", [])),
        },
    ])

    display(appendix_turn_summary)
    display(pd.DataFrame(appendix_saved_history))

### How This Appendix Connects to the App Later

#### Backend

- Add `sqlalchemy` and `psycopg[binary]` to `smartLearn-AI/smartlearn-backend/requirements.txt`.
- Put `DAY3_DB_URL=...` in `.env`.
- In `smartlearn-backend/services/rag.py`, add the table models and the history-store helpers.
- In `smartlearn-backend/main.py`, keep `/upload` and `GET /documents/{chat_id}/file` as they are, and let `/chat` choose the PostgreSQL-backed helper only when `DAY3_DB_URL` is configured.

#### Frontend

- For normal asking and cited answers, `App.jsx`, `ChatPanel.jsx`, and `PdfPreview.jsx` can stay unchanged because the `/chat` response shape does not change.
- If you later want old turns to reappear after a page refresh, add one history-loading route such as `GET /chat/history?chat_id=...` and let `ChatPanel` initialize from it.

#### Restart Behavior

- Saved messages can survive in PostgreSQL.
- The current uploaded PDF record still lives in `documents[chat_id]`.
- After a backend restart, the simplest demo path is: upload the same PDF again, then continue the same `chat_id`.

### Verify After You Connect It to the App

1. Set `DAY3_DB_URL` and restart the backend.
2. Upload `pdf1.pdf` with one real `chat_id` such as `day2-demo`.
3. Ask one question and then one follow-up.
4. Confirm PostgreSQL now has the saved history for that `chat_id` (usually four message rows for two question-answer turns).
5. Restart the backend, upload the same PDF again, and ask a follow-up such as `Give one more detail from that page.`.
6. Confirm the answer can still use the earlier saved turns for the same `chat_id`.
7. If the frontend page refreshes and old turns are not drawn yet, that is expected until you add a separate history-loading route.

### Appendix A Checkpoint

- [ ] I can explain what PostgreSQL stores in this appendix and what still stays in memory.
- [ ] I can configure `DAY3_DB_URL` and create the history tables.
- [ ] I can write and read one conversation by `chat_id` through SQLAlchemy.
- [ ] I can run one DB-backed two-turn test from the notebook.
- [ ] I know why the frontend can keep the same ask/render contract for the basic appendix path.
- [ ] I know which extra route is needed if I want old turns to reappear after a page refresh.

## Extra: Try Improving Your Project Next

Make your SmartLearn project stand out! You may think about some of these:

- Decide when RAG is actually needed. Some short, local, or follow-up questions may be answerable from the current page or recent history without another full retrieval step.
- Handle summary-style questions better. When `top_k=3` is too narrow, try a larger candidate pool, a two-pass summary, or a retrieve-then-merge flow.
- Add a reranker. Retrieve quickly first, then reorder the top candidates before answer generation for better recall and answer quality.
- Compress long multi-turn history. Keep the key facts, cited pages, and open threads instead of sending every old turn forever.
- Support custom models and local LLMs. Let users choose a cloud model they like or one local model server path (ollama, vLLM, etc) at the frontend.
- Make citations more precise in the UI. User can jump not only to a page, but also to a paragraph anchor or a highlighted span in the viewer.
- And more...